CarDealership.Web/Models/CarPartialViewModel.cs
using System;
using CarDealership.Domain.ReadModels;

namespace CarDealership.Web.Models
{
    public class CarPartialViewModel
    {
        public Car Car { get; set; }
        public Customer Customer { get; set; }
        public DateTime OrderDate { get; set; }
        public SalesPerson SalesPerson { get; set; }
        public decimal SoldFor { get; set; }
    }
}

CarDealership.Web/Controllers/CarController.cs
using System;
using CarDealership.Domain.Cars.Queries;
using CarDealership.Domain.Framework.Queries;
using Microsoft.AspNetCore.Mvc;

namespace CarDealership.Web.Controllers
{
    public class CarController : Controller
    {
        private readonly IQueryProcessor _queryProcessor;

        public CarController(IQueryProcessor queryProcessor)
        {
            _queryProcessor = queryProcessor;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var query = new GetAllMakesQuery();
            var makes = _queryProcessor.Process(query);
            return View(makes);
        }

        public IActionResult Make(Guid id)
        {
            var query = new GetMakeQuery(id);
            var make = _queryProcessor.Process(query);
            return View(make);
        }

        public IActionResult Model(Guid id)
        {
            var query = new GetModelQuery(id);
            var model = _queryProcessor.Process(query);
            return View(model);
        }
    }
}

CarDealership.Web/Controllers/CarPurchaseController.cs
using System;
using System.Linq;
using CarDealership.Domain.CarPurchases.Queries;
using CarDealership.Domain.Framework.Queries;
using CarDealership.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace CarDealership.Web.Controllers
{
    public class CarPurchaseController : Controller
    {
        private readonly IQueryProcessor _queryProcessor;

        public CarPurchaseController(IQueryProcessor queryProcessor)
        {
            _queryProcessor = queryProcessor;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var query = new GetAllCarPurchasesQuery();
            var sales = _queryProcessor.Process(query);
            var vm = new SalesViewModel()
            {
                Sales = sales,
                StartDate = sales.First().OrderDate,
                EndDate = DateTime.Today
            };
            return View(vm);
        }

        [HttpPost]
        public IActionResult Index(DateTime startDate, DateTime endDate)
        {
            var query = new SearchForCarPurchasesQuery(startDate, endDate);
            var sales = _queryProcessor.Process(query);
            var vm = new SalesViewModel
            {
                Sales = sales,
                StartDate = startDate,
                EndDate = endDate
            };
            return View(vm);
        }

        [HttpGet("[controller]/{id}")]
        public IActionResult Get(Guid id)
        {
            var query = new GetCarPurchaseQuery(id);
            var purchase = _queryProcessor.Process(query);
            return View(purchase);
        }
    }
}

CarDealership.Web/Controllers/CustomerController.cs
using System;
using CarDealership.Domain.Customers.Queries;
using CarDealership.Domain.Framework.Queries;
using CarDealership.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace CarDealership.Web.Controllers
{
    public class CustomerController : Controller
    {
        private readonly IQueryProcessor _queryProcessor;

        public CustomerController(IQueryProcessor queryProcessor)
        {
            _queryProcessor = queryProcessor;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var query = new GetAllCustomersQuery();
            var customers = _queryProcessor.Process(query);
            var vm = new CustomerViewModel
            {
                Customers = customers,
                SearchTerm = string.Empty
            };
            return View(vm);
        }

        [HttpPost]
        public IActionResult Index(string searchTerm)
        {
            if (string.IsNullOrWhiteSpace(searchTerm))
            {
                return Index();
            }

            var query = new SearchForCustomersQuery(searchTerm);
            var customers = _queryProcessor.Process(query);
            var vm = new CustomerViewModel
            {
                Customers = customers,
                SearchTerm = searchTerm
            };
            return View(vm);
        }

        [HttpGet("[controller]/{id}")]
        public IActionResult Get(Guid id)
        {
            var query = new GetCustomerQuery(id);
            var customer = _queryProcessor.Process(query);
            return View(customer);
        }
    }
}

CarDealership.Web/Controllers/SalesPersonController.cs
using System;
using CarDealership.Domain.Framework.Queries;
using CarDealership.Domain.SalesPersons.Queries;
using CarDealership.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace CarDealership.Web.Controllers
{
    public class SalesPersonController : Controller
    {
        private readonly IQueryProcessor _queryProcessor;

        public SalesPersonController(IQueryProcessor queryProcessor)
        {
            _queryProcessor = queryProcessor;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var query = new GetAllSalesPersonsQuery();
            var salesPersons = _queryProcessor.Process(query);
            var vm = new SalesPersonViewModel
            {
                SalesPersons = salesPersons,
                SearchTerm = string.Empty
            };
            return View(vm);
        }

        [HttpPost]
        public IActionResult Index(string searchTerm)
        {
            if (string.IsNullOrWhiteSpace(searchTerm))
            {
                return Index();
            }

            var query = new SearchForSalesPersonsQuery(searchTerm);
            var salesPersons = _queryProcessor.Process(query);
            var vm = new SalesPersonViewModel
            {
                SalesPersons = salesPersons,
                SearchTerm = searchTerm
            };
            return View(vm);
        }

        [HttpGet("[controller]/{id}")]
        public IActionResult Get(Guid id)
        {
            var query = new GetSalesPersonQuery(id);
            var salesPerson = _queryProcessor.Process(query);
            return View(salesPerson);
        }
    }
}

CarDealership.Web/Views/Shared/_CarPartial.cshtml
@model CarPartialViewModel

<div class="card mb-3">
    <div class="card-body">
        <div class="row">
            <div class="col-lg-2 mr-5 text-center">
                <i class="fas fa-car fa-10x"></i>
            </div>
            <div class="col">
                <h5 class="card-title">@Model.Car.Make @Model.Car.Model</h5>
                <p class="card-text">
                    Owned by:
                    @Html.ActionLink($"{Model.Customer.Name} {Model.Customer.Surname}", "Get", "Customer", new {id = Model.Customer.Id}, new {@class = "badge badge-dark"})
                </p>
                <p class="card-text">Order date: @Model.OrderDate.ToString("D")</p>
                <p class="card-text">
                    Sales person:
                    @Html.ActionLink(Model.SalesPerson.Name, "Get", "SalesPerson", new { id = Model.SalesPerson.Id}, new {@class = "badge badge-dark"})
                </p>
                <p class="card-text">Recommended price: @Model.Car.RecommendPrice.ToString("C") - sold for: @Model.SoldFor.ToString("C")</p>
                @if (Model.Car.Extras.Any(o => !string.IsNullOrWhiteSpace(o)))
                {
                    <strong>Extras:</strong>
                    <ul>
                        @foreach (var extra in @Model.Car.Extras)
                        {
                            <li>@extra</li>
                        }
                    </ul>
                }
            </div>
        </div>
    </div>
</div>

CarDealership.Web/Views/Shared/_Header.cshtml
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    @Html.ActionLink("Car Dealership", "Index", "Home", null, new {@class = "navbar-brand"})
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            @Html.ActionLink("Home", "Index", "Home", null, new {@class = "nav-item nav-link"})
            @Html.ActionLink("Customers", "Index", "Customer", null, new {@class = "nav-item nav-link"})
            @Html.ActionLink("Sales Persons", "Index", "SalesPerson", null, new {@class = "nav-item nav-link"})
            @Html.ActionLink("Car Purchases", "Index", "CarPurchase", null, new {@class = "nav-item nav-link"})
            @Html.ActionLink("Cars", "Index", "Car", null, new {@class = "nav-item nav-link"})
        </div>
    </div>
</nav>

CarDealership.Web/Views/Shared/_Layout.cshtml
@{ 
    var currentYear = DateTime.Now.Year;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>@ViewData["Title"] - Car Dealership</title>
    
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    @await Html.PartialAsync("_Header")

    <main class="container">
        @RenderBody()
        <hr />
    </main>

    <footer>
        <div class="container">
            <p>&copy; @currentYear - Car Dealership</p>
        </div>
    </footer>

    @await Html.PartialAsync("_CookieConsentPartial")

    <environment include="Development">
        <script src="~/lib/jquery/jquery.slim.js" asp-append-version="true"></script>
        <script src="~/lib/popper/popper.js" asp-append-version="true"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js" asp-append-version="true"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>

        <link rel="stylesheet" href="~/lib/fontawesome/css/all.css" asp-append-version="true" />
    </environment>
    <environment exclude="Development">
        <script src="~/lib/jquery/jquery.slim.min.js" asp-append-version="true"></script>
        <script src="~/lib/popper/popper.min.js" asp-append-version="true"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.min.js" asp-append-version="true"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>

        <link rel="stylesheet" href="~/lib/fontawesome/css/all.min.css" asp-append-version="true" />
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>