CarDealership.Web/Models/CarPartialViewModel.cs
using System;
using CarDealership.Domain.ReadModels;

namespace CarDealership.Web.Models
{
    public class CarPartialViewModel
    {
        public Car Car { get; set; }
        public Customer Customer { get; set; }
        public DateTime OrderDate { get; set; }
        public SalesPerson SalesPerson { get; set; }
        public decimal SoldFor { get; set; }
    }
}

CarDealership.Web/Models/CustomerViewModel.cs
using System.Collections.Generic;
using CarDealership.Domain.ReadModels;

namespace CarDealership.Web.Models
{
    public class CustomerViewModel
    {
        public string SearchTerm { get; set; }
        public List<Customer> Customers { get; set; }
    }
}

CarDealership.Web/Models/ErrorViewModel.cs
using System;

namespace CarDealership.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CarDealership.Web/Models/SalesPersonViewModel.cs
using System.Collections.Generic;
using CarDealership.Domain.ReadModels;

namespace CarDealership.Web.Models
{
    public class SalesPersonViewModel
    {
        public string SearchTerm { get; set; }
        public List<SalesPerson> SalesPersons { get; set; }
    }
}

CarDealership.Web/Models/SalesViewModel.cs
using System;
using System.Collections.Generic;
using CarDealership.Domain.ReadModels;

namespace CarDealership.Web.Models
{
    public class SalesViewModel
    {
        public List<CarPurchase> Sales { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
    }
}

CarDealership.Web/Controllers/CarController.cs
using System;
using CarDealership.Domain.Cars.Queries;
using CarDealership.Domain.Framework.Queries;
using Microsoft.AspNetCore.Mvc;

namespace CarDealership.Web.Controllers
{
    public class CarController : Controller
    {
        private readonly IQueryProcessor _queryProcessor;

        public CarController(IQueryProcessor queryProcessor)
        {
            _queryProcessor = queryProcessor;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var query = new GetAllMakesQuery();
            var makes = _queryProcessor.Process(query);
            return View(makes);
        }

        public IActionResult Make(Guid id)
        {
            var query = new GetMakeQuery(id);
            var make = _queryProcessor.Process(query);
            return View(make);
        }

        public IActionResult Model(Guid id)
        {
            var query = new GetModelQuery(id);
            var model = _queryProcessor.Process(query);
            return View(model);
        }
    }
}

CarDealership.Web/ViewComponents/CarPurchasesByMakeViewComponent.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using CarDealership.Domain.Cars.Queries;
using CarDealership.Domain.Framework.Queries;
using CarDealership.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace CarDealership.Web.ViewComponents
{
    public class CarPurchasesByMakeViewComponent : ViewComponent
    {
        private readonly IQueryProcessor _queryProcessor;

        public CarPurchasesByMakeViewComponent(IQueryProcessor queryProcessor)
        {
            _queryProcessor = queryProcessor;
        }

        public async Task<IViewComponentResult> InvokeAsync(Guid makeId)
        {
            var query = new GetCarPurchasesByMakeQuery(makeId);
            var purchases = _queryProcessor.Process(query);

            var vm = purchases.Select(o => new CarPartialViewModel
                {
                    Car = o.Car,
                    SalesPerson = o.SalesPerson,
                    Customer = o.Customer,
                    OrderDate = o.OrderDate,
                    SoldFor = o.PricePaid
                }).ToList();

            return View(vm);
        }
    }
}

CarDealership.Web/ViewComponents/CarPurchasesByModelViewComponent.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using CarDealership.Domain.Cars.Queries;
using CarDealership.Domain.Framework.Queries;
using CarDealership.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace CarDealership.Web.ViewComponents
{
    public class CarPurchasesByModelViewComponent : ViewComponent
    {
        private readonly IQueryProcessor _queryProcessor;

        public CarPurchasesByModelViewComponent(IQueryProcessor queryProcessor)
        {
            _queryProcessor = queryProcessor;
        }

        public async Task<IViewComponentResult> InvokeAsync(Guid modelId)
        {
            var query = new GetCarPurchasesByModelQuery(modelId);
            var purchases = _queryProcessor.Process(query);

            var vm = purchases.Select(o => new CarPartialViewModel
            {
                Car = o.Car,
                SalesPerson = o.SalesPerson,
                Customer = o.Customer,
                OrderDate = o.OrderDate,
                SoldFor = o.PricePaid
            }).ToList();

            return View(vm);
        }
    }
}

CarDealership.Web/Views/Car/Index.cshtml
@model List<CarDealership.Domain.ReadModels.Make>

@{
    ViewData["Title"] = "Car Page";
}

<div class="row">
    @foreach (var make in Model)
    {
        <div class="col-lg mb-3">
            <a class="card-link text-dark" href="@Url.Action("Make", "Car", new {id = @make.Id})">
                <div class="card">
                    <div class="text-center">
                        <i class="fas fa-car fa-10x"></i>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title text-center">@make.Name</h5>
                    </div>
                </div>
            </a>
        </div>
    }
</div>

CarDealership.Web/Views/Car/Make.cshtml
@model CarDealership.Domain.ReadModels.Make

@{
    ViewData["Title"] = Model.Name;
}

<h5>@Model.Name</h5>

<div class="row mb-3">
    @foreach (var carModel in Model.Models)
    {
        <div class="col-lg mb-3">
            <a class="card-link text-dark" href="@Url.Action("Model", "Car", new {id = @carModel.Id})">
                <div class="card">
                    <div class="text-center">
                        <i class="fas fa-car fa-10x"></i>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title text-center">@carModel.Name</h5>
                    </div>
                </div>
            </a>
        </div>
    }
</div>

<h5>Car Purchases with @Model.Name</h5>

@await Component.InvokeAsync("CarPurchasesByMake", new { makeId = Model.Id })

CarDealership.Web/Views/Car/Model.cshtml
@model CarDealership.Domain.ReadModels.Model

@{
    ViewData["Title"] = Model.Name;
}

<h5>@Model.Name</h5>

@await Component.InvokeAsync("CarPurchasesByModel", new { modelId = Model.Id })