Presentation/CarDealership.Presentation.Website/Areas/CacheTest/Models/CacheTestViewModel.cs
using System;

namespace CarDealership.Presentation.Website.Areas.CacheTest.Models
{
    [Serializable]
    public class CacheTestViewModel
    {
        public string Time { get; set; }
    }
}

Presentation/CarDealership.Presentation.Website/Models/ErrorViewModel.cs
using System;

namespace CarDealership.Presentation.Website.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Presentation/CarDealership.Presentation.Website/Areas/CacheTest/Controllers/CacheController.cs
using CarDealership.Domain.Caching;
using CarDealership.Presentation.Website.Areas.CacheTest.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using System;
using System.Threading.Tasks;

namespace CarDealership.Presentation.Website.Areas.CacheTest.Controllers
{
    [Area("CacheTest")]
    public class CacheController : Controller
    {
        private const string CacheKey = "Controller:Test";
        private readonly IMultiLayerCache _cache;
        private readonly IMemoryCache _memoryCache;

        public CacheController(IMultiLayerCache cache, IMemoryCache memoryCache)
        {
            _cache = cache;
            _memoryCache = memoryCache;
        }

        public async Task<IActionResult> Index()
        {
            var value = DateTime.UtcNow;
            await _cache.GetOrAddAsync(CacheKey, () =>  new CacheTestViewModel() { Time = value.ToLongTimeString() });
            return View();
        }

        public async Task<IActionResult> MultiLayer()
        {
            var model = await _cache.GetAsync<CacheTestViewModel>(CacheKey);
            return View(model);
        }

        public async Task<IActionResult> Distributed()
        {
            _memoryCache.Remove(CacheKey);
            var model = await _cache.GetAsync<CacheTestViewModel>(CacheKey);
            return View(model);
        }
    }
}

Presentation/CarDealership.Presentation.Website/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using CarDealership.Presentation.Website.Models;

namespace CarDealership.Presentation.Website.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Presentation/CarDealership.Presentation.Website/Areas/CacheTest/Views/Cache/Distributed.cshtml
@model CarDealership.Presentation.Website.Areas.CacheTest.Models.CacheTestViewModel

@Html.DisplayFor(m => m)

@Html.ActionLink("Back", "Index")

Presentation/CarDealership.Presentation.Website/Areas/CacheTest/Views/Cache/Index.cshtml
<ul>
    <li>
        @Html.ActionLink("MultiLayer", "MultiLayer")
    </li>
    <li>
        @Html.ActionLink("Distributed", "Distributed")
    </li>
</ul>

Presentation/CarDealership.Presentation.Website/Areas/CacheTest/Views/Cache/MultiLayer.cshtml
@model CarDealership.Presentation.Website.Areas.CacheTest.Models.CacheTestViewModel

@Html.DisplayFor(m => m)

@Html.ActionLink("Back", "Index")

Presentation/CarDealership.Presentation.Website/Areas/CacheTest/Views/DisplayTemplates/CacheTestViewModel.cshtml
@model CarDealership.Presentation.Website.Areas.CacheTest.Models.CacheTestViewModel

<span>@Model.Time</span>

<span>@Html.ActionLink("Back", "Index")</span>

Presentation/CarDealership.Presentation.Website/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

<a asp-area="CacheTest" asp-controller="Cache" asp-action="Index">CacheTest</a>

Presentation/CarDealership.Presentation.Website/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CarDealership.Presentation.Website</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CarDealership.Presentation.Website</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - CarDealership.Presentation.Website - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>